### ISSUE TITLE
add Context

### ISSUE THREAD

**Issue by lain0** [HeavyTechRuby/bddsm#21]
so it can be used like:
```ruby
BDDSM.describe '.context' do
  let(:user) { create(:user) }
 
  context 'when user is valid' do
    it { expected(user).to be valid }
  end
 
   context 'when user is invalid' do
     let(:user) { User.new }
   
     it { expected(user).to be invalid }
   end
end
```

**Comment by fartem** [comment]
@sergio-fry can I try to solve this ticket?

**Comment by fartem** [comment]
@lain0, can you give some examples (gems or other sources) that can helps in development of this feature?

**Comment by lain0** [comment]
@fartem  not shure if this can help you in some way but https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/example_group.rb

and this: 
https://github.com/rspec/rspec-core/blob/2ba0f10fe68948e5ee9addd569b4694f0245aa71/script/ignores#L17
where in  # script/ignores       
```ruby
alias_method :context, :describe
```
