### ISSUE TITLE
Add License to repository

### ISSUE THREAD

**Issue by fartem** [HeavyTechRuby/bddsm#40]
Lack of a license is one of the warnings when publishing a `bddsm` gem. I will try to fix it if @sergio-fry tells me what license I should to add.

<img width="657" alt="Screenshot 2024-07-18 at 11 47 10" src="https://github.com/user-attachments/assets/0c065fb6-6dac-4640-8eee-b0769d543184">

**Comment by sergio-fry** [comment]
lets use MIT
