### ISSUE TITLE
Publish gem on RubyGems

### ISSUE THREAD

**Issue by fartem** [HeavyTechRuby/bddsm#44]
Right now we can download `bddsm` only from GitHub packages and with authentication (because GHP are private). Maybe we can publish latest version of framework on RubyGems?

**Comment by sergio-fry** [comment]
Works just fine:

```
$ gem i bddsm
Successfully installed bddsm-0.1.6
Parsing documentation for bddsm-0.1.6
Done installing documentation for bddsm after 0 seconds
1 gem installed

```

Could you provide steps to reproduce?

**Comment by fartem** [comment]
@sergio-fry, apparently I had some kind of mistake and didn't find the gem on RubyGems. Works fine, thanks.
